trigger:
  - master

jobs:
  - job: Linux
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: "12.x"
        displayName: "Install Node.js"
      - script: |
          cd client
          npm ci
          npm run package-linux
          ls dist
          tar -czf dist/ExLuminous-linux-x64.tar.gz dist/ExLuminous-linux-x64
        displayName: "Build for Linux"
      - publish: $(System.DefaultWorkingDirectory)/client/dist/ExLuminous-linux-x64.tar.gz
        artifact: ExLuminousLinux
  - job: Mac
    pool:
      vmImage: "macOS-latest"
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: "12.x"
        displayName: "Install Node.js"
      - script: |
          cd client
          npm ci
          npm run package-mac
          ls dist
          tar -czf dist/ExLuminous-darwin-x64.tar.gz dist/ExLuminous-darwin-x64
        displayName: "Build for Mac"
      - publish: $(System.DefaultWorkingDirectory)/client/dist/ExLuminous-darwin-x64.tar.gz
        artifact: ExLuminousMac
  - job: Windows
    pool:
      vmImage: "windows-latest"
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: "12.x"
        displayName: "Install Node.js"
      - powershell: .\client\build-win.ps1
        displayName: "Build for Windows"
      - publish: $(System.DefaultWorkingDirectory)/client/dist/ExLuminous-win32-x64.zip
        artifact: ExLuminousWindows
